Docs: Updating run-dev.sh instructions on variables not needed.
aws/amazon-genomics-cli pull request #343
Opened 2022-02-17 23:24 UTC by josuebc

Issue #, if available:

**Description of Changes**
Removing not used instructions from the run-dev.sh section to match the current behavior of the script.

[//]: #  (A description of the change that you made and the new user experience that it creates)

**Description of how you validated changes**
N/A

[//]: #  (A description of you validated your changes and any relevant logs that show your change works)

**Checklist**

- [x] If this change would make any existing documentation invalid, I have included those updates within this PR
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] I have linted my code before raising the PR
- [x] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-02-17 23:59 UTC, tneely approved these changes

2022-02-18 00:40 UTC, evanyui requested changes
Don't we still need these environment variables if the dev users were to run https://github.com/aws/amazon-genomics-cli/blob/main/packages/cdk/lib/util/index.ts#L36-L48 to test out a custom image?
I think the section of readme here should be a new option to run dev code, but at a lower level, which I think its what "run from development code 'manually'" mean there.

2022-02-21 19:10 UTC, josuebc commented
@evanyui I updated the instructions to reflect you feedback.

2022-02-21 20:09 UTC, evanyui approved these changes

2022-02-22 00:25 UTC, tneely approved these changes

2022-02-28 21:39 UTC, merged