feat: Added ability to pass custom environment variables to a Workflow Job
aws/amazon-genomics-cli pull request #404
Opened 2022-04-10 07:32 UTC by kankou-aliaksei

Issue #, if available:

**Description of Changes**

[//]: #  This adds ability to pass environment variables from to a Workflow Job

**Description of how you validated changes**

[//]: #  Set value [{ "name": "k1", "value": { "k2": 15 } }, { "name": "k3", "value": 10 }] (for example) for CUSTOM_WORKFLOW_JOB_ENVIRONMENTS environment variable in the WES Adapter thus k1 and k3 environment variables will be available in a Workflow Job.

**Checklist**

- [x ] If this change would make any existing documentation invalid, I have included those updates within this PR
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ x] I have linted my code before raising the PR
- [x ] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-04-10 17:28 UTC, markjschreiber commented
Can you provide some more information on the intended use? The Batch Adapter runs as a lambda function so how would a user provide these environment variables to Lambda using AGC?

2022-04-14 14:21 UTC, kankou-aliaksei commented
> Can you provide some more information on the intended use? The Batch Adapter runs as a lambda function so how would a user provide these environment variables to Lambda using AGC?

Hi @markjschreiber 

Good point. I have implemented --adapterCustomEnvs flag to pass parameters through Amazon Genomics Cli.

The main reason for this feature is to pass envs to an Adapter lambda to customize an Adapter lambda.

Also feature is to pass miniwdl config parameters to miniwdl-aws extention dynamically (through CUSTOM_WORKFLOW_JOB_ENVIRONMENTS Adapter Lambda env).

For example by running 

agc account activate --adapterCustomEnvs "CUSTOM_WORKFLOW_JOB_ENVIRONMENTS=[{ \"name\": \"MINIWDL__AWS__BOTO3_RETRIES\", \"value\": { \"max_attempts\": 15, \"mode\": \"standard\" } }, { \"name\": \"MINIWDL__AWS__DESCRIBE_PERIOD\", \"value\": 10 }, { \"name\": \"MINIWDL__AWS__SUBMIT_PERIOD\", \"value\": 10 }]"

I can override:
1) boto3 batch client retry policy
2) batch job describe period
3) batch job submit period
etc...

Also after activating account we can override 	/agc/_common/adapterCustomEnvs SSM parameter or CUSTOM_WORKFLOW_JOB_ENVIRONMENTS environment for Adapter Lambda by SDK for example to change parameter values.

2022-04-19 20:35 UTC, markjschreiber requested changes
Could you also add some documentation to `site/content/en/docs/Concepts/accounts.md`? Specifically the section on the `activate` command.

2022-04-19 20:35 UTC, markjschreiber commented on packages/cdk/lib/stacks/engines/miniwdl-engine-construct.ts
> +      customEnvs: props.contextParameters.adapterCustomEnvs,
Use `customWesEnvVars` for this engine and all other engine constructs so that it is more obvious where these variables are being used.

2022-04-27 13:02 UTC, closed without merging